name = "Rocket"
description = "Rocket is a web framework for Rust that makes it simple to write fast, secure web applications without sacrificing flexibility, usability, or type safety."
url = "https://rocket.rs/"
github_repo = "SergioBenitez/Rocket"
language = "rust"
